### ISSUE TITLE
New tests are not created if admin notices are disabled

### ISSUE THREAD

**Issue by sabrina-zeidan** [sabrina-zeidan/speedguard#12]
As per [ticket](https://wordpress.org/support/topic/unable-to-add-any-page/#post-14350066).
Possible solution: Separate add-new-test functionality from admin notices display.

**Comment by atomicbongorg** [comment]
Hi Sabrina,

Any luck with this defect?
Great plugin btw!

Regards,
Ankit.

**Comment by sabrina-zeidan** [comment]
Fixed in 1.8.5
